### PR TITLE
Updated information

### PR DESCRIPTION
**Pull request by benjaminthegreat**
big bear

### CODE REVIEW

**Comment by envunderscoreexplosion** [comment]
elaborate

**Comment by benjaminthegreat** [comment]
replaced all Brown Bears iwht Big Bears to be More Accurate

**Comment by envunderscoreexplosion** [comment]
elaboare or closed

**Comment by benjaminthegreat** [comment]
I Used Find and Replace to Replace the word Brown with the word Big so on your Website about Big Bears it actualyl says Big Bears instead of Brown. I also went back and fixed hte links to Brown Bears to work

**Comment by envunderscoreexplosion** [comment]
epic fail

**Pull request closed without merging**
